# Generated by Django 6.0.7 on 2026-07-16 03:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='previous_sales',
            field=models.IntegerField(default=0),
        ),
    ]
